<a href="https://colab.research.google.com/github/rudmaxx/DTA_Python/blob/main/Homework/numpy_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏠 Домашнє завдання — NumPy

**До тьюторіалу:** Pandas + Matplotlib: Аналіз даних з нуля

---
### Правила виконання
- Кожне завдання виконуй в окремій клітинці
- Не використовуй цикли там де можна обійтись операціями NumPy
- Після виконання — запусти клітинку і перевір що результат виглядає правильно
- Якщо застряг — поверніться до відповідного розділу тьюторіалу

**Оцінювання:** кожне завдання — 1 бал. Фінальний проєкт — 3 бали. Всього: **14 балів**

---

## Розділ 1 — Масиви ndarray та атрибути

> **Що повторюємо:** `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`,
> атрибути `.shape`, `.ndim`, `.size`, `.dtype`

### ✏️ Завдання 1.1

У тебе є дані середньомісячних температур у Харкові за рік (°C):

```
-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3
```

1. Створи NumPy масив із цих значень і назви його `temps`
2. Виведи масив
3. Виведи: кількість вимірів (`ndim`), форму (`shape`), кількість елементів (`size`), тип даних (`dtype`)
4. Виведи мінімальну, максимальну температуру та середньорічну (округли до 1 знаку)

In [ ]:
import numpy as np

# Твій код:
temps = np.array([-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3])
print("1-2. Масив", temps)
print("3. Кількість вимірів:", temps.ndim,"\n", "  Форма:", temps.shape,"\n","  Кількість елементів:", temps.size,"\n","  Тип даних :", temps.dtype)
print("4. Мінімальна температура:",temps.min(),"\n", "  Максимальна температура:",temps.max(),"\n","  Середньорічна температура:",temps.mean().round(1))

1-2. Масив [-5 -4  2 10 17 21 23 22 16  9  2 -3]
3. Кількість вимірів: 1 
   Форма: (12,) 
   Кількість елементів: 12 
   Тип даних : int64
4. Мінімальна температура: -5 
   Максимальна температура: 23 
   Середньорічна температура: 9.2


### ✏️ Завдання 1.2

Створи таблицю планових продажів для 3 менеджерів на 4 квартали.

1. Створи матрицю `plan` розміром **3×4**, заповнену значенням `50` (тис. грн) — використай `np.full()`
2. Виведи матрицю
3. Виведи її форму та загальну кількість елементів
4. Створи другу матрицю `bonus` розміром **3×4** із нулів — менеджери ще не отримали бонусів
5. Виведи суму `plan + bonus` і переконайся що вона рівна `plan`

In [ ]:
# Твій код:
plan = np.full((3, 4), 50)

print("-" * 5," 1-2.Створи матрицю plan","-" * 5)
print(plan,"\n")

print("-" * 5," 3.Форма/Кількість елементів","-" * 5)
print(" Форма:",plan.shape,"\n","Кількість елементів:",plan.size,"\n")

print("-" * 5," 4.bonus","-" * 5)
bonus = np.zeros((3, 4))
print(bonus,"\n")

print("-" * 5,"5.plan + bonus","-" * 5)
print((bonus) + (plan))


-----  1-2.Створи матрицю plan -----
[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]] 

-----  3.Форма/Кількість елементів -----
 Форма: (3, 4) 
 Кількість елементів: 12 

-----  4.bonus -----
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

----- 5.plan + bonus -----
[[50. 50. 50. 50.]
 [50. 50. 50. 50.]
 [50. 50. 50. 50.]]


---
## Розділ 2 — Індексація та зрізи

> **Що повторюємо:** індексація 1D і 2D масивів, зрізи `[start:stop:step]`,
> вибір рядків та стовпців матриці

### ✏️ Завдання 2.1

Є масив денних продажів магазину за 2 тижні (14 днів):

```python
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])
```

Виконай такі вибірки **без циклів**, лише через зрізи:
1. Продажі першого тижня (дні 1–7)
2. Продажі другого тижня (дні 8–14)
3. Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день — використай індексацію списком `[[5,6,12,13]]`
4. Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...)
5. Масив у зворотному порядку

In [ ]:
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])

# Твій код:
print("1.Продажі першого тижня:",sales[:7],"\n")
print("2.Продажі другого тижня:",sales[7:],"\n")
print("3.Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день:",sales[[5,6,12,13]],"\n")
print("4.Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...):",sales[::2],"\n")
print("5.Масив у зворотному порядку:",sales[::-1].reshape(2, 7),"\n")

1.Продажі першого тижня: [320 415 290 480 350 620 580] 

2.Продажі другого тижня: [310 440 305 510 370 650 595] 

3.Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день: [620 580 650 595] 

4.Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...): [320 290 350 580 440 510 650] 

5.Масив у зворотному порядку: [[595 650 370 510 305 440 310]
 [580 620 350 480 290 415 320]] 



### ✏️ Завдання 2.2

Є матриця оцінок студентів: **4 студенти × 5 предметів**.

```python
grades = np.array([
    [85, 72, 91, 78, 88],   # Олена
    [63, 88, 74, 95, 70],   # Максим
    [90, 65, 82, 70, 94],   # Аня
    [75, 80, 68, 85, 79],   # Богдан
])
```

1. Виведи всі оцінки Олени (перший рядок)
2. Виведи оцінки всіх студентів з 3-го предмету (третій стовпець)
3. Виведи підматрицю: оцінки Максима та Ані з предметів 2–4 (рядки 1–2, стовпці 1–3)
4. Виведи оцінки останнього студента з останнього предмету

In [ ]:
grades = np.array([
    [85, 72, 91, 78, 88],
    [63, 88, 74, 95, 70],
    [90, 65, 82, 70, 94],
    [75, 80, 68, 85, 79],
])

# Твій код:
print("1.Виведи всі оцінки Олени:",grades[0, :],"\n")
print("2.Виведи оцінки всіх студентів з 3-го предмету:",grades[:, 2],"\n")
print("3.Виведи підматрицю: оцінки Максима та Ані з предметів 2–4:","\n",grades[1:3, 1:4],"\n")
print("4.Виведи оцінки останнього студента з останнього предмету:",grades[3,4],"\n")


1.Виведи всі оцінки Олени: [85 72 91 78 88] 

2.Виведи оцінки всіх студентів з 3-го предмету: [91 74 82 68] 

3.Виведи підматрицю: оцінки Максима та Ані з предметів 2–4: 
 [[88 74 95]
 [65 82 70]] 

4.Виведи оцінки останнього студента з останнього предмету: 79 



---
## Розділ 3 — Математичні операції та векторизація

> **Що повторюємо:** арифметика з масивами, `np.sqrt()`, `np.round()`,
> агрегатні функції `.sum()`, `.mean()`, `.std()`, `.min()`, `.max()`, `np.median()`

### ✏️ Завдання 3.1

Є масив цін товарів у доларах. Виконай **без циклів**:

```python
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])
```

1. Переведи ціни в гривні (курс: **1 USD = 41.5 UAH**), результат округли до 2 знаків
2. Нарахуй ПДВ 20% — помнож гривневі ціни на 1.2, округли до 2 знаків
3. Знайди: мінімальну, максимальну, середню ціну з ПДВ
4. Знайди суму всіх товарів з ПДВ — це загальна вартість кошика
5. Виведи результати з поясненнями

In [ ]:
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])
prices_uah = prices_usd * 41.5
prices_uah_pdv = prices_uah * 1.2
# Твій код:
print("1. Ціни в гривні (курс: 1 USD = 41.5 UAH)",prices_uah.round(2),"грн\n")
print("2.Ціни з ПДВ 20%",prices_uah_pdv.round(2),"грн\n")
print("3.Мінімальна ціна з ПДВ: ",prices_uah_pdv.min(),"грн\n"," Мінімальна ціна з ПДВ:",prices_uah_pdv.max(),"грн\n"," Середня ціна з ПДВ:",prices_uah_pdv.mean().round(2),"грн\n")
print("4.Загальна вартість кошика: ",prices_uah_pdv.sum().round(2),"грн\n")

1. Ціни в гривні (курс: 1 USD = 41.5 UAH) [ 663.58 1763.75  332.   5187.5  1400.62 2788.8   414.58] грн

2.Ціни з ПДВ 20% [ 796.3  2116.5   398.4  6225.   1680.75 3346.56  497.5 ] грн

3.Мінімальна ціна з ПДВ:  398.4 грн
  Мінімальна ціна з ПДВ: 6225.0 грн
  Середня ціна з ПДВ: 2151.57 грн

4.Загальна вартість кошика:  15061.01 грн



### ✏️ Завдання 3.2

Є дані про кількість товарів на складі та їх собівартість.
Виконай **без циклів**:

```python
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']
```

1. Порахуй загальну вартість кожного товару на складі (`quantity * cost_each`)
2. Знайди загальну вартість всього складу
3. Знайди товар з найбільшою сумарною вартістю — використай `np.argmax()`
4. Знайди товар з найменшою сумарною вартістю — `np.argmin()`
5. Виведи середню вартість одного найменування на складі

In [ ]:
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']

# Твій код:
total_each = quantity * cost_each
total = total_each.sum()
print("1. Загальна вартість кожного товару на складі",total_each,"грн\n")
print("2. Загальну вартість всього складу",total,"грн\n")
print("3. Товар з найбільшою сумарною вартістю: ",total_each.argmax(),"(Монітор)\n")
print("4. Товар з найменшою сумарною вартістю: ",total_each.argmin(),"(Зошит)\n")
print("5. Середню вартість одного найменування на складі: ",total_each.mean().round(2),"грн\n")

1. Загальна вартість кожного товару на складі [ 30000  81000  13500 171000  28500  24000  45000] грн

2. Загальну вартість всього складу 393000 грн

3. Товар з найбільшою сумарною вартістю:  3 (Монітор)

4. Товар з найменшою сумарною вартістю:  2 (Зошит)

5. Середню вартість одного найменування на складі:  56142.86 грн



---
## Розділ 4 — Булеве маскування і фільтрація

> **Що повторюємо:** булеві маски, фільтрація `arr[mask]`,
> `np.where()`, `.sum()` для підрахунку True

### ✏️ Завдання 4.1

Є масив часу виконання замовлень у хвилинах (норма — до 30 хв):

```python
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])
```

1. Знайди всі замовлення, виконані **вчасно** (≤ 30 хв)
2. Знайди всі **запізнілі** замовлення (> 30 хв)
3. Порахуй кількість вчасних і запізнілих
4. Знайди відсоток запізнілих замовлень (округли до 1 знаку)
5. Яка середня затримка серед запізнілих замовлень?

In [ ]:
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])

# Твій код:
in_time = delivery_time[delivery_time <= 30]
out_of_time = delivery_time[delivery_time > 30]
print("1. Всі замовлення, виконані вчасно: ",in_time)
print("2. Всі запізнілі замовлення: ",out_of_time)
print("3. Кількість вчасних замовлень",len(in_time))
print("   Кількість запізнілих замовлень",out_of_time.size)
print("4. Відсоток запізнілих замовлень",(out_of_time.size) / len(delivery_time)* 100, "%")
print("5. Середня затримка серед запізнілих замовлень",out_of_time.mean(),"хв")


1. Всі замовлення, виконані вчасно:  [22 28 19 27 24 26 18 29 23 20]
2. Всі запізнілі замовлення:  [35 41 55 33 48 31 52 38 44 36]
3. Кількість вчасних замовлень 10
   Кількість запізнілих замовлень 10
4. Відсоток запізнілих замовлень 50.0 %
5. Середня затримка серед запізнілих замовлень 41.3 хв


### ✏️ Завдання 4.2

Є масив щоденних продажів за місяць. Використай `np.where()`:

```python
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)
```

1. Знайди дні з продажами **вище середнього** за місяць
2. Порахуй скільки таких днів
3. За допомогою `np.where()` створи масив `status`:
   - `'Гарний день'` — якщо продажі вище середнього
   - `'Звичайний день'` — якщо нижче або рівно
4. Виведи перші 10 днів: продажі та їх статус поряд

In [ ]:
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)

# Твій код:
avg = daily.mean()
# high = daily[daily > avg]
high = np.where(daily > avg)
print('1. Дні з продажами вище середнього:',high,'\n')
print('2. Кількість таких днів:',high[0].size,'\n')
status = np.where(daily > avg,'Гарний день','Звичайний день')
print('3. Гарний/Звичайний день:',status,'\n')
print("4. Перші 10 днів:")
for i in range(10):
    print(' ',i, daily[i], '-', status[i])

1. Дні з продажами вище середнього: (array([ 1,  5,  7,  9, 12, 14, 16, 18, 20, 21, 22, 23, 24, 28]),) 

2. Кількість таких днів: 14 

3. Гарний/Звичайний день: ['Звичайний день' 'Гарний день' 'Звичайний день' 'Звичайний день'
 'Звичайний день' 'Гарний день' 'Звичайний день' 'Гарний день'
 'Звичайний день' 'Гарний день' 'Звичайний день' 'Звичайний день'
 'Гарний день' 'Звичайний день' 'Гарний день' 'Звичайний день'
 'Гарний день' 'Звичайний день' 'Гарний день' 'Звичайний день'
 'Гарний день' 'Гарний день' 'Гарний день' 'Гарний день' 'Гарний день'
 'Звичайний день' 'Звичайний день' 'Звичайний день' 'Гарний день'
 'Звичайний день'] 

4. Перші 10 днів:
  0 202 - Звичайний день
  1 535 - Гарний день
  2 370 - Звичайний день
  3 206 - Звичайний день
  4 171 - Звичайний день
  5 800 - Гарний день
  6 120 - Звичайний день
  7 714 - Гарний день
  8 221 - Звичайний день
  9 566 - Гарний день


---
## Розділ 5 — reshape та сортування

> **Що повторюємо:** `.reshape()`, `.flatten()`, `np.sort()`, `np.argsort()`

### ✏️ Завдання 5.1

Є 1D масив з 24 показників продажів (по годинах за добу):

```python
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])
```

1. Перетвори масив у матрицю **6×4** (6 блоків по 4 години) і виведи
2. Знайди суму продажів у кожному 4-годинному блоці (по рядках)
3. Відсортуй вихідний 1D масив за **зростанням** і виведи
4. Знайди **індекси** годин відсортованих за зростанням продажів — `np.argsort()`
5. Виведи топ-3 найпродуктивніших години (їхні номери, рахуючи з 0)

In [ ]:
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])

# Твій код:
hourly_6x4 = hourly.reshape(6,4)
print('1.Матриця 6×4')
print(hourly_6x4)
print('2.Сума продажів у кожному 4-годинному блоці')
print('',hourly_6x4.sum(axis=1))
print('3.Відсортований вихідний 1D масив за зростанням')
print('',np.sort(hourly))
print('4.Індекси годин відсортованих за зростанням продажів')
print('',np.argsort(hourly))


top3 = np.argsort(hourly)[-3:][::-1]
print('5.Топ-3 найпродуктивніших години')
print('',top3)

1.Матриця 6×4
[[12  8  5  3]
 [ 4  9 18 35]
 [52 61 58 64]
 [70 67 55 48]
 [53 62 74 68]
 [45 30 22 15]]
2.Сума продажів у кожному 4-годинному блоці
 [ 28  66 235 240 257 112]
3.Відсортований вихідний 1D масив за зростанням
 [ 3  4  5  8  9 12 15 18 22 30 35 45 48 52 53 55 58 61 62 64 67 68 70 74]
4.Індекси годин відсортованих за зростанням продажів
 [ 3  4  2  1  5  0 23  6 22 21  7 20 15  8 16 14 10  9 17 11 13 19 12 18]
5.Топ-3 найпродуктивніших години
 [18 12 19]


---
## Розділ 6 — Генерація випадкових чисел

> **Що повторюємо:** `np.random.seed()`, `np.random.randint()`,
> `np.random.normal()`, `np.random.choice()`

### ✏️ Завдання 6.1

Змоделюй результати маркетингового опитування 50 клієнтів.

1. Встанови `np.random.seed(99)`
2. Згенеруй масив `ages` — вік 50 клієнтів: цілі числа від 18 до 65
3. Згенеруй масив `scores` — оцінки задоволеності (нормальний розподіл, середнє=7, σ=1.5), округли до 1 знаку
4. Обріж `scores` так щоб значення були від 1 до 10 — `np.clip(arr, 1, 10)`
5. Виведи:
   - середній вік клієнтів
   - середню оцінку задоволеності
   - кількість клієнтів з оцінкою >= 8 («задоволені»)
   - відсоток задоволених

In [ ]:
# Твій код:
np.random.seed(99)
ages = np.random.randint(18, 66, size=50)
scores = (np.random.normal(loc=7, scale=1.5, size=50)).round(1)
print("2. Згенеруй масив ages")
print(ages,"\n")
print("3. Згенеруй масив scores")
print(scores,"\n")
scores = np.clip(scores, 1, 10)
print("4. Обріж scores так щоб значення були від 1 до 10")
print(scores,"\n")
avg = ages.mean()
print("5.1. Середній вік клієнтів: ",avg,"років")
scr_avg = scores.mean().round(2)
print("5.2. Середня оцінка задоволеності: ",scr_avg)
zad = scores[scores >= 8]
print("5.3. Кількість клієнтів з оцінкою >= 8: ",len(zad))
print("5.4. Відсоток задоволених: ",(zad.size) / 50 * 100, "%")

---
## 🏆 Фінальний проєкт — Аналіз даних магазину

> **Використовуємо все з тьюторіалу разом**

Ти аналітик даних невеликого магазину електроніки.
Тобі передали масив продажів за 8 тижнів (56 днів).

Виконай повний аналіз та дай відповіді на запитання керівника.

In [ ]:
# Дані — не змінюй цю клітинку
np.random.seed(2024)
base = np.random.randint(200, 800, 56)

# Вихідні продаються краще
weekend_boost = np.array([1 if i % 7 in [5, 6] else 0 for i in range(56)])
sales_56 = (base + weekend_boost * np.random.randint(100, 300, 56)).astype(int)

print('Дані отримано. Масив sales_56 готовий до аналізу.')
print(f'Елементів: {sales_56.size}, форма: {sales_56.shape}')


### Запитання 1 — Загальна статистика (Розділ 1, 3)
Виведи:
- Загальна виручка за 56 днів
- Середньоденна виручка (округли до 2 знаків)
- Мінімальний та максимальний денний продаж
- Стандартне відхилення (наскільки продажі «скачуть»)

In [58]:
# Твій код:
total = sales_56.sum()
print('Загальна виручка за 56 днів: ',total,'\n')
print('Середньоденна виручка: ',sales_56.mean().round(2),'\n')
print('Мінімальний денний продаж:',sales_56.min(), 'та максимальний денний продаж: ',sales_56.max(),'\n')
print('Стандартне відхилення:', sales_56.std().round(2))

Загальна виручка за 56 днів:  31819 

Середньоденна виручка:  568.2 

Мінімальний денний продаж: 222 та максимальний денний продаж:  1072 

Стандартне відхилення: 195.52


### Запитання 2 — Тижневий аналіз (Розділ 5)
1. Перетвори `sales_56` у матрицю **8×7** (8 тижнів по 7 днів)
2. Знайди виручку кожного тижня (сума по рядках)
3. Знайди найкращий тиждень і виведи його номер (рахуючи з 1) та суму
4. Знайди середньоденну виручку по кожному дню тижня (середнє по стовпцях)
5. Виведи який день тижня в середньому найприбутковіший (0=Пн, 6=Нд)

In [57]:
# Твій код:
sales = sales_56.reshape(8,7)
print('1. Матриця 8x7: ')
print(sales,'\n')

total_week = sales.sum(axis=1)
print('2. Виручка по тижням: ')
print(total_week,'\n')

best_week = total_week.max()
best_week_index = total_week.argmax()
print(f'3. Найкращий тиждень: {best_week_index + 1} і його сумма: {best_week} \n ')


tdm = sales.mean(axis=0).round(2)
print('4. Середньоденна виручка по кожному дню тижня: ')
print(tdm,'\n')

best_day = tdm.argmax()
print(f'5. Найприбутковіший день тижня: {best_day}, середня виручка: {tdm[best_day]:.2f}')

1. Матриця 8x7: 
[[ 706  739  748  646  383  556  777]
 [ 427  274  522  680  708  465  845]
 [ 447  402  551  567  723  404  469]
 [ 254  314  383  754  297  472 1072]
 [ 773  510  769  798  510  824  852]
 [ 336  297  591  637  296  735  408]
 [ 661  447  734  558  339  710  779]
 [ 559  661  229  222  454  872  673]] 

2. Виручка по тижням: 
[4555 3921 3563 3546 5036 3300 4228 3670] 

3. Найкращий тиждень: 5 і його сумма: 5036 
 
4. Середньоденна виручка по кожному дню тижня: 
[520.38 455.5  565.88 607.75 463.75 629.75 734.38] 

5. Найприбутковіший день тижня: 6, середня виручка: 734.38


### Запитання 3 — Фільтрація та маскування (Розділ 4)
1. Знайди кількість **«слабких» днів** — продажі нижче 400 грн
2. Знайди кількість **«сильних» днів** — продажі вище 700 грн
3. Яка середня виручка у слабкі дні і яка у сильні?
4. Створи масив `labels` за допомогою `np.where()`:
   - `'Слабкий'` якщо < 400
   - `'Сильний'` якщо > 700
   - `'Нормальний'` в решті випадків (підказка: вкладений `np.where`)
5. Виведи перші 14 днів: продажі та їх мітки

In [ ]:
# Твій код:
weak_days = sales[sales < 400]
print(f'1. Кількість «слабких» днів — продажі нижче 400 грн: {len(weak_days)}')

good_days = sales[sales > 700]
print(f'2. Кількість «сильних» днів — продажі вище 700 грн: {len(good_days)}')

avg_weak = weak_days.mean().round(2)
avg_good = good_days.mean().round(2)
print(f'3. Середня виручка у «слабкі» дні: {avg_weak} грн\n   Середня виручка у «сильні» дні: {avg_good} грн' )

labels = np.where(sales_56 < 400,'Слабкий', np.where(
        sales_56 > 700,
        'Сильний',
        'Нормальний')
)
print("5. Перші 14 днів:")
for i in range(14):
    print(f"День {i+1}: {sales_56[i]} - {labels[i]}")

---
## ✅ Підсумок

| Розділ | Завдання | Балів | Виконано |
|--------|----------|-------|----------|
| 1 — Масиви ndarray | 1.1, 1.2 | 2 | ☐ |
| 2 — Індексація та зрізи | 2.1, 2.2 | 2 | ☐ |
| 3 — Математичні операції | 3.1, 3.2 | 2 | ☐ |
| 4 — Булеве маскування | 4.1, 4.2 | 2 | ☐ |
| 5 — reshape та сортування | 5.1 | 1 | ☐ |
| 6 — Генерація випадкових | 6.1 | 1 | ☐ |
| 🏆 Фінальний проєкт | Питання 1–3 | 3 | ☐ |
| **Разом** | | **13** | |
